name: Android-CI

on:
  pull_request:
    
jobs:
 
  Android-CI:
    name: "Android-CI"
    runs-on: Windows
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - run: python framework_launcher.py -cf "C:\GM-TestFramework\configs\config_android.json"
        working-directory: GM-TF      
