name: CI

on:
  pull_request:

  workflow_dispatch:
    inputs:
       CONFIG_FILE:
         description: "CONFIG_FILE"
         required: true

jobs:
 
  CI:
    name: "CI"
    runs-on: Windows
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - name: Running Manually
        if: github.event_name == 'workflow_dispatch'
        run: python framework_launcher.py -cf ${{ secrets.CONFIG_FOLDER }}\${{ github.event.inputs.CONFIG_FILE }}
        working-directory: GM-TF        
      - name: Running on PR
        if: github.event_name == 'pull_request'
        run: python framework_launcher.py -cf ${{ secrets.CONFIG_FOLDER }}\${{ github.event.inputs.CONFIG_FILE }}
        working-directory: GM-TF       
      - name: Upload tests Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: .\GM-TF\workspace\results\tests\
          continue-on-error: true  
      - name: Upload summary Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: summary_file
          path: .\GM-TF\workspace\summary.json
          continue-on-error: true        

  # Slack-Notification:
  #   name: "Slack-Notification"
  #   runs-on: Windows
  #   needs: [ CI ]
  #   if: always()
  #   steps:
  #     - name: Sending Test Result to Slack Channel
  #       uses: adrey/slack-file-upload-action@master
  #       with:
  #         token: ${{ secrets.SLACK_TOKEN }}
  #         path: .\GM-TF\workspace\summary.json
  #         channel: 'C0545RKQ4MV'