name: CI

on:
  pull_request:

  workflow_dispatch:
    inputs:
       CONFIG_FILE:
         description: "CONFIG_FILE"
         required: true
       RSS_Feed:
         description: "RSS_Feed"
         required: false

jobs:
 
  CI:
    name: "CI"
    runs-on: Windows
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - name: Running Manually
        run: | 
          if ($env:github_event_name -eq 'workflow_dispatch' -and $env:INPUT_RSS_FEED -eq 'true') {
            python framework_launcher.py -cf "$env:CONFIG_FOLDER\$env:INPUT_CONFIG_FILE" -f $env:INPUT_RSS_FEED
          }
          else {
            python framework_launcher.py -cf "$env:CONFIG_FOLDER\$env:INPUT_CONFIG_FILE"
          }         
        working-directory: GM-TF  
        continue-on-error: true      
      - name: Running on PR
        if: github.event_name == 'pull_request'
        run: python framework_launcher.py -cf ${{ secrets.CONFIG_FOLDER }}\config_ci.json              
        working-directory: GM-TF    
        continue-on-error: true            
      - name: Upload tests Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: .\GM-TF\workspace\results\tests\
        continue-on-error: true  
      - name: Upload summary Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: summary_file
          path: .\GM-TF\workspace\summary.json
        continue-on-error: true        
