name: iOS-CI

on:
  pull_request:
    
jobs:
 
  iOS-CI:
    name: "iOS-CI"
    runs-on: macOS
    steps: 
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - run: python framework_launcher.py -cf ${{ secrets.IOS_CONFIG_FILE }}
        working-directory: GM-TF 
      - name: Upload tests Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: .\GM-TF\workspace\results\tests\
          if-no-files-found: error   
      - name: Upload summary Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: summary_file
          path: .\GM-TF\workspace\summary.json
          if-no-files-found: error           
      # - name: Upload to slack step
      #   uses: adrey/slack-file-upload-action@master
      #   with:
      #     token: ${{ secrets.SLACK_TOKEN }}
      #     path: "./GM-TF/workspace/summary.json"
      #     channel: ${{ secrets.SLACK_CHANNEL_ID }}        
      # - uses: slackapi/slack-github-action@v1.23.0
      #   id: slack
      #   with:
      #    channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
      #    payload-file-path: ".\\GM-TF\\workspace\\summary.json"
      #    slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"         
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}        