name: Windows-CI

on:
  pull_request:
    
jobs:
 
  Windows-CI:
    name: "Windows-CI"
    runs-on: Windows
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - run: python3 framework_launcher.py -cf ${{ secrets.Windows_Config_Folder }}