name: Windows-CI

on:
  pull_request:
    
jobs:
 
  Windows-CI:
    name: "Windows-CI"
    runs-on: Windows
    steps:
      - name: Check out the GM-TestFramework repo
        uses: actions/checkout@v3
        with:
          path: GM-TF
      - run: .\setup.bat
        working-directory: GM-TF
        shell: cmd
      - run: python framework_launcher.py -cf ${{ secrets.WINDOWS_CONFIG_FOLDER }}
        working-directory: GM-TF      
      - uses: slackapi/slack-github-action@v1.23.0
        id: slack
        with:
         channel-id: 'C0508TFEW4Q'
         payload-file-path: ".\\workspace\\summary.json"
         slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"         
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}        